version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis
  celery:
    build: .
    command: celery -A yourmagazine worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery