# Generated by Django 3.0 on 2019-12-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='ebook',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
